baseURL = "https://magicbroccoli.de/"
languageCode = "de-DE"
title = "Magical Broccoli"
theme = "blackburn"
author = "nico"
# Shown in the side menu
copyright = "&copy; 2017. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "just magical"
  brand = "Blackburn"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  custom_css = ["css/my.css"]
  custom_js = ["js/my.js"]
  enableRobotsTXT = true

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "XMPP Server"
    pre = "<i class='fa fa-delicious' aria-hidden='true'></i>"
    weight = 2
    identifier = "xmpp"
    url = "/xmpp/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags' aria-hidden='true'></i>"
    weight = 4
    identifier = "tags"
    url = "/tags/"
  [[menu.main]]
    name = "Terms of Use"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 7
    identifier = "Terms of Use"
    url = "/termsofuse/"
  [[menu.main]]
    name = "Datenschutz"
    pre = "<i class='fa fa-user-secret' aria-hidden='true'></i>"
    weight = 8
    identifier = "Datenschutz"
    url = "/datenschutz/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-address-book-o' aria-hidden='true'></i>"
    weight = 9
    url = "/contact/"
  [[menu.main]]
    name = "Impressum"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 10
    identifier = "Impressum"
    url = "/impressum/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  jabber = "broccoli@magicbroccoli.de"

  # Techie
  github = "mightyBroccoli"
  bitbucket = "mightyBroccoli"

  # Gaming
  # steam = "*"

  # Other
  keybase = "mightyBroccoli"
