baseurl = "https://magicbroccoli.de/"
languageCode = "de-DE"
title = "Magic Broccoli"
author = "nico"
#copyright = "&copy; 2017. All rights reserved."
copyright = "All rights reserved."
canonifyurls = true
paginate = 4
theme = "hugo-bootstrap"
DefaultContentLanguage = "de"

enableRobotsTXT = true
noTimes = true

[params.widgets]
  recent_articles = false
  categories = true
  tags = true
  tag_cloud = true

[blackfriday]
hrefTargetBlank = true

[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = -110
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "XMPP"
    pre = "<i class='fa fa-delicious'></i>"
    weight = -100
    identifier = "xmpp"
    url = "/xmpp/"

[[menu.main]]
    name = "Register"
    pre = "<i class='fa fa-plus' fa-fw'></i>"
    weight = -99
    identifier = "register"
    url = "/register/"

  [[menu.main]]
      name = "Tutorials"
      pre = "<i class='fa fa-question-circle' fa-fw'></i>"
      weight = -98
      identifier = "tutorial"
      url = "/page/tutorial/"

[[menu.main]]
    name = "About me"
    pre = "<i class='fa fa-info-circle'></i>"
    weight = -90
    identifier = "contact"
    url = "/contact/"

[[menu.footer]]
    name = "Privacy Policy"
    weight = -110
    identifier = "privacy"
    url = "/datenschutz/"

[[menu.footer]]
    name = "Terms of Use"
    weight = -120
    identifier = "termsofuse"
    url = "/termsofuse/"

[[menu.footer]]
    name = "Impressum"
    weight = -130
    identifier = "impress"
    url = "/impressum/"
